### ISSUE TITLE
Support GHC 9.8?

### ISSUE THREAD

**Issue by tfausak** [ocharles/weeder#141]
I'm not sure how challenging this will be. But I figured I'd make an issue to track it 😄 

Same idea as #109.

**Comment by tfausak** [comment]
Naively trying to build with GHC 9.8.1 runs into this error:

```
src/Weeder.hs:62:5: error: [GHC-61689]
    Module ‘GHC.Types.Avail’ does not export ‘GreName’.
   |
62 |   , GreName( NormalGreName, FieldGreName )
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I'm not familiar enough with GHC to know what `GreName`s are. Seems to be related to record fields? https://hackage.haskell.org/package/ghc-9.6.4/docs/GHC-Types-Avail.html#t:GreName

At any rate, it seems like `GreName`s don't exist in GHC 9.8. So something's going to have to change in `analyseExport`.
