### ISSUE TITLE
Support GHC 9.4?

### ISSUE THREAD

**Issue by tfausak** [ocharles/weeder#109]
I didn't see an issue for this yet so I thought I'd make one. 

`cborg` needs to be updated to support GHC 9.4: https://github.com/well-typed/cborg/pull/304

Ignoring bounds, trying to build `weeder` itself runs into a problem:

```
src/Weeder/Main.hs:43:80: error:
    Module ‘GHC.Iface.Ext.Binary’ does not export ‘NameCacheUpdater’
   |
43 | import GHC.Iface.Ext.Binary ( HieFileResult( HieFileResult, hie_file_result ), NameCacheUpdater( NCU ), readHieFileWithVersion )
   |                                                                                ^^^^^^^^^^^^^^^^^^^^^^^
```

It looks like the name cache updater went away in GHC 9.4:

- 9.2: `readHieFile :: NameCacheUpdater -> FilePath -> IO HieFileResult` https://hackage.haskell.org/package/ghc-9.2.5/docs/GHC-Iface-Ext-Binary.html#v:readHieFile
- 9.4: `readHieFile :: NameCache -> FilePath -> IO HieFileResult` https://hackage.haskell.org/package/ghc-9.4.4/docs/GHC-Iface-Ext-Binary.html

**Comment by ocharles** [comment]
Thanks for the issue. I think I will probably only be able to work on this when I get our work codebase working with 9.4. Currently there are a few upstream blockers to that (e.g., `repa`). Once I can build all work components, weeder will be a blocker and I'll be forced to do this! I of course welcome contributions, but otherwise that's the order I'll be tackling things.
